### ISSUE TITLE
suggestion: make "target 'foo' is not installed" a warning, not a notice

### ISSUE THREAD

**Issue by jack-oquin** [fkie/catkin_lint#23]
I frequently ignore most of the other "notices", but this one is important when preparing a package for release.

**Comment by jack-oquin** [comment]
Looking at the code, the same point could be made for UNINSTALLED_EXPORT_LIB and maybe MISSING_INSTALL_INCLUDE. (I am unsure what [info.commands](https://github.com/fkie/catkin_lint/blob/master/src/catkin_lint/checks/build.py#L358) actually contains.

I'll be happy to provide a pull request, if you agree.

**Comment by roehling** [comment]
`info.commands` is the list of all commands in the `CMakeLists.txt`. Basically, if there is no `install()` command at all, I assume that people don't care about proper installation, since most packages work just fine from develspace. But I agree that this diagnostic is important for package releases.

**Comment by jack-oquin** [comment]
Looks great. Thanks!
