### ISSUE TITLE
Check alphabetical order for listed components?

### ISSUE THREAD

**Issue by wkentaro** [fkie/catkin_lint#27]
I mean

* packages names in run_depend and build_depend
* file names for msg and srv

**Comment by wkentaro** [comment]
I think it should be ordered in alphabetical order, because people can duplicate and mis some dependencies or files if there are lots of things.

**Comment by roehling** [comment]
For message and service files, `catkin_int` already issues a notice (`-W2`) if the lists are not sorted. Since `catkin_lint` relies on `catkin_pkg` for parsing the `package.xml`, it cannot check the order in that file. It does, however, check for missing dependencies, and I could add a check for duplicate entries.

**Comment by wkentaro** [comment]
> For message and service files, catkin_int already issues a notice (-W2) if the lists are not sorted. Since catkin_lint relies on catkin_pkg for parsing the package.xml

Thanks, I found that `catkin_lint` has that feature already after creating this issue.
