### ISSUE TITLE
Parent directory are not parsed correctly 

### ISSUE THREAD

**Issue by Minipada** [fkie/catkin_lint#53]
Hi, I have in a ROS package a global cmakelists.txt used in multiple packages in the parent folder.
Catkin lint doesn't detect it and reports

    my-package: CMakeLists.txt(4): error: include() needs missing file '/global_config.cmake'

In my package CMakeLists.txt:

    include(../global_config.cmake)

The `..` is ignored. Any way to solve this?

**Comment by roehling** [comment]
`catkin_lint` complained for the wrong reasons, but the issue is that your package uses a file that is not part of the package and depends on a very particular filesystem layout. If you were to release your package as official ROS package, you could no longer rely on `global_config.cmake` being where you expect it.

Still, you can override `catkin_lint`'s complaint. Starting with the next release, add the line `#catkin_lint: ignore external_file` before that `include()`. For now, you can silence the error with `#catkin_lint: ignore missing_file`.
