### ISSUE TITLE
Symlinks are not supported / honored

### ISSUE THREAD

**Issue by Timple** [fkie/catkin_lint#64]
I get the following notice:
`test_package: notice: package path name '/home/user/repos/test_package.git' differs from package name`

But this folder is symlinked to `/home/user/ros_ws/test_package`
This is also the location where I run catkin_lint.

My suggestion would be to use 
```python
info.path = os.path.abspath(path)
```
here:
https://github.com/fkie/catkin_lint/blob/ab0be8ce462047ce2644e34cda563b955011fe8f/src/catkin_lint/linter.py#L589

This would keep the symlinks. Which we have there for a reason :)

**Comment by roehling** [comment]
We used to do symlinking in the past because `catkin_make` cannot deal very well with building a subset of packages. If that is your concern, I recommend you take a look at [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/), which does pretty much everything better than `catkin_make`, and I for one was happy to get rid of that symlink overhead.

Regardless, your proposed change is probably a good idea, because `catkin_lint` should make as few assumptions as possible on how people organize their workspace.
