### ISSUE TITLE
pkg_check_module not recognised as build_depend

### ISSUE THREAD

**Issue by wxmerkt** [fkie/catkin_lint#71]
As discovered in https://github.com/ros-planning/moveit/pull/1550#issuecomment-545868017:

Modules from pkg_check_modules are not interpreted as dependencies.

**Comment by roehling** [comment]
The `eigenpy` package seems to be a part of the ROS distribution and declares itself to be a native catkin package in its manifest, which is why `catkin_lint` expects and enforces the proper way to configure a catkin dependency via `find_package()`.

There is not much I can do besides adding a special case exempting `eigenpy` from this rule, which I'm not very keen on doing. I suggest that the `eigenpy` maintainer either goes "all the way" and provides the proper interface, or adds the `<build_type>cmake</build_type>` to indicate that `eigenpy` is not a real catkin package, which would make `catkin_lint` stop complaining, too. 

Until then, I recommend whitelisting with `#catkin_lint: ignore unconfigured_build_depend`.

**Comment by wxmerkt** [comment]
Thank you for the detailed analysis @roehling. We are in the process of making `eigenpy` a proper third-party package so I understand the error now.
